# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Run tests
      run: |
        git clone https://github.com/alphasea-dapp/alphasea.git
        cd alphasea
        yarn install
        npx hardhat compile
        npx hardhat node &
        npx hardhat run --network localhost scripts/deploy.js
        cd ../

        echo '    extra_hosts:' >> docker-compose-dev.yml
        echo '      - "host.docker.internal:host-gateway"' >> docker-compose-dev.yml

        docker-compose -f docker-compose-dev.yml run --rm agent bash scripts/test.sh
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        docker-compose -f docker-compose-dev.yml run --rm agent flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        docker-compose -f docker-compose-dev.yml run --rm agent flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
